PRAGMA foreign_keys = ON;

ALTER TABLE users
ADD COLUMN full_name TEXT NOT NULL DEFAULT '';

ALTER TABLE users
ADD COLUMN website_url TEXT NOT NULL DEFAULT '';

ALTER TABLE users
ADD COLUMN social_instagram TEXT NOT NULL DEFAULT '';

ALTER TABLE users
ADD COLUMN social_x TEXT NOT NULL DEFAULT '';

ALTER TABLE users
ADD COLUMN social_tiktok TEXT NOT NULL DEFAULT '';

ALTER TABLE users
ADD COLUMN birthday TEXT NOT NULL DEFAULT '';

ALTER TABLE users
ADD COLUMN country TEXT NOT NULL DEFAULT '';
